### ISSUE TITLE
Crash on S10E/BlueStacks on latest release

### ISSUE THREAD

**Issue by Ceikry** [2009scape/2009Scape-mobile#2]
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.downthecrop.scape.debug/net.kdt.pojavlaunch.JavaGUILauncherActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2668)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
	at android.content.ComponentName.<init>(ComponentName.java:128)
	at android.content.Intent.<init>(Intent.java:4900)
	at net.kdt.pojavlaunch.sound.JAudioManager.init(JAudioManager.java:13)
	at net.kdt.pojavlaunch.JavaGUILauncherActivity.onCreate(JavaGUILauncherActivity.java:272)
	at android.app.Activity.performCreate(Activity.java:6785)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1146)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
	... 9 more

**Comment by downthecrop** [comment]
App only supports ARM/ARM64 currently. 

x86 emulators are out of scope due to architecture dependent JRE binaries of Pojav.


This error references JMessageHandler. Start by COMPLETLY UNINSALLING THE PREVIOUS VERSION and then installing beta4.apk https://github.com/2009scape/2009Scape-mobile/releases/tag/Alpha
